title: Oracle Enterprise Landing Zone 2.0
description: Oracle Enterprise Landing Zone 2.0 developed by OCI
schemaVersion: 1.0.0
version: "1.0.0"
locale: en
variableGroups:
  - title: Variables required for Landing Zone (OLZ Express) provisioning
    visible: true
    variables:
      - region
      - tenancy_ocid
      - current_user_ocid
      - prod_environment_prefix
      - prod_hub_vcn_cidr_block
      - prod_hub_public_subnet_cidr_block
      - prod_hub_private_subnet_cidr_block
      - enable_network_firewall_prod
  - title: Invisible Variables
    visible: false
    variables:
      - api_fingerprint
      - api_private_key_path
      - api_private_key
      - prod_retention_policy_duration_amount
      - prod_retention_policy_duration_time_unit
      - prod_external_master_encryption_key
      - prod_enable_vpn
      - prod_cpe_display_name
      - prod_cpe_ip_address
      - prod_ipsec_display_name
      - prod_ipsec_connection_static_routes
      - prod_cpe_vendor
      - prod_ipsec_routing_type
      - prod_tunnel_a_display_name
      - prod_customer_bgp_asn
      - prod_bgp_cust_tunnela_ip
      - prod_bgp_oci_tunnela_ip
      - prod_shared_secret
      - prod_tunnel_b_display_name
      - prod_enable_fastconnect
      - prod_enable_drg_rpc
      - prod_enable_traffic_threat_log
      - prod_nfw_subnet_type
      - prod_nfw_instance_name
      - prod_nfw_instance_policy
      - prod_domain_admin_email
      - prod_network_admin_group_name
      - prod_security_admin_group_name
      - prod_iam_admin_group_name
      - prod_platform_admin_group_name
      - prod_ops_admin_group_name
      - prod_enable_shared_tools
      - prod_enable_dmz
      - prod_vault_type
      - prod_vault_replica_region
      - prod_enable_vault_replication
      - prod_create_master_encryption_key
      - prod_enable_budget
      - prod_budget_amount
      - prod_budget_alert_rule_threshold
      - prod_budget_alert_rule_message
      - prod_budget_alert_rule_recipients
      - prod_enable_internet_gateway_hub
      - prod_enable_nat_gateway_hub
      - prod_enable_service_gateway_hub
      - prod_igw_hub_check
      - prod_nat_gw_hub_check
      - prod_service_gw_hub_check
      - prod_shared_tools_vcn_cidr_block
      - prod_shared_tools_subnet1_cidr_block
      - prod_shared_tools_subnet2_cidr_block
      - prod_shared_tools_subnet3_cidr_block
      - prod_shared_tools_subnet4_cidr_block
      - prod_shared_tools_vcn_display_name
      - prod_shared_tools_vcn_dns_label
      - prod_shared_tools_subnet1_dns_label
      - prod_shared_tools_subnet2_dns_label
      - prod_shared_tools_subnet3_dns_label
      - prod_shared_tools_subnet4_dns_label
      - prod_enable_tools_internet_gateway
      - prod_enable_tools_nat_gateway
      - prod_enable_tools_service_gateway
      - prod_enable_tagging
      - prod_cost_center_tagging
      - prod_geo_location_tagging
      - prod_network_topic_endpoints
      - prod_secops_topic_endpoints
      - prod_platform_topic_endpoints
      - prod_identity_topic_endpoints
      - prod_enable_security_monitoring_alarms
      - prod_enable_network_monitoring_alarms
      - prod_workload_compartment_names
      - prod_additional_workload_subnets_cidr_blocks
      - prod_shared_tools_workload_subnets_cidr_blocks
      - archive_log_retention_policy_duration_amount
      - archive_log_retention_policy_duration_time_unit
      - archive_external_master_encryption_key
      - enable_vpn_or_fastconnect
      - fastconnect_provider
      - virtual_circuit_bandwidth_shape
      - virtual_circuit_display_name
      - provider_service_key_name
      - fastconnect_routing_policy
      - virtual_circuit_type
      - customer_primary_bgp_peering_ip
      - oracle_primary_bgp_peering_ip
      - customer_secondary_bgp_peering_ip
      - oracle_secondary_bgp_peering_ip
      - virtual_circuit_customer_asn
      - virtual_circuit_is_bfd_enabled
      - bgp_md5auth_key
      - customer_onprem_ip_cidr
      - resource_label
      - is_baseline_deploy
      - home_compartment_name
      - enable_compartment_delete
      - break_glass_user_email_list
      - domain_license_type
      - enable_cloud_guard
      - cloud_guard_target_tenancy
      - is_create_alarms
      - is_service_connector_limit
      - onboard_log_analytics
      - is_nonprod_env_deploy
      - backup_bgp_md5auth_key
      - backup_customer_onprem_ip_cidr
      - backup_customer_primary_bgp_peering_ip
      - backup_customer_secondary_bgp_peering_ip
      - backup_enable_network_firewall_nonprod
      - backup_enable_network_firewall_prod
      - backup_enable_traffic_threat_log_nonprod
      - backup_enable_traffic_threat_log_prod
      - backup_enable_vpn_or_fastconnect
      - backup_fastconnect_provider
      - backup_fastconnect_routing_policy
      - backup_igw_hub_check
      - backup_nat_gw_hub_check
      - backup_nfw_instance_name_nonprod
      - backup_nfw_instance_name_prod
      - backup_nfw_instance_policy_nonprod
      - backup_nfw_instance_policy_prod
      - backup_nfw_subnet_type_nonprod
      - backup_nfw_subnet_type_prod
      - backup_nfw_use_existing_network_nonprod
      - backup_nfw_use_existing_network_prod
      - backup_nonprod_additional_workload_subnets_cidr_blocks
      - backup_nonprod_bastion_client_cidr_block_allow_list
      - backup_nonprod_bgp_cust_tunnela_ip
      - backup_nonprod_bgp_oci_tunnela_ip
      - backup_nonprod_cpe_display_name
      - backup_nonprod_cpe_ip_address
      - backup_nonprod_cpe_vendor
      - backup_nonprod_create_master_encryption_key
      - backup_nonprod_customer_bgp_asn
      - backup_nonprod_enable_fastconnect
      - backup_nonprod_enable_internet_gateway_hub
      - backup_nonprod_enable_nat_gateway_hub
      - backup_nonprod_enable_nat_gateway_spoke
      - backup_nonprod_enable_service_gateway_hub
      - backup_nonprod_enable_service_gateway_spoke
      - backup_nonprod_enable_vpn
      - backup_nonprod_hub_private_subnet_cidr_block
      - backup_nonprod_hub_public_subnet_cidr_block
      - backup_nonprod_hub_vcn_cidr_block
      - backup_nonprod_ipsec_connection_static_routes
      - backup_nonprod_ipsec_display_name
      - backup_nonprod_ipsec_routing_type
      - backup_nonprod_private_subnet_cidr_block
      - backup_nonprod_public_subnet_cidr_block
      - backup_nonprod_retention_policy_duration_amount
      - backup_nonprod_retention_policy_duration_time_unit
      - backup_nonprod_shared_secret
      - backup_nonprod_spoke_subnet_app_cidr_block
      - backup_nonprod_spoke_subnet_db_cidr_block
      - backup_nonprod_spoke_subnet_web_cidr_block
      - backup_nonprod_spoke_vcn_cidr
      - backup_nonprod_tunnel_a_display_name
      - backup_nonprod_tunnel_b_display_name
      - backup_nonprod_vault_enable_replication
      - backup_nonprod_vault_replica_region
      - backup_nonprod_vault_type
      - backup_nonprod_workload_cidr
      - backup_oracle_primary_bgp_peering_ip
      - backup_oracle_secondary_bgp_peering_ip
      - backup_prod_additional_workload_subnets_cidr_blocks
      - backup_prod_bastion_client_cidr_block_allow_list
      - backup_prod_bgp_cust_tunnela_ip
      - backup_prod_bgp_oci_tunnela_ip
      - backup_prod_cpe_display_name
      - backup_prod_cpe_ip_address
      - backup_prod_cpe_vendor
      - backup_prod_create_master_encryption_key
      - backup_prod_customer_bgp_asn
      - backup_prod_enable_fastconnect
      - backup_prod_enable_internet_gateway_hub
      - backup_prod_enable_nat_gateway_hub
      - backup_prod_enable_nat_gateway_spoke
      - backup_prod_enable_service_gateway_hub
      - backup_prod_enable_service_gateway_spoke
      - backup_prod_enable_vpn
      - backup_prod_hub_private_subnet_cidr_block
      - backup_prod_hub_public_subnet_cidr_block
      - backup_prod_hub_vcn_cidr_block
      - backup_prod_ipsec_connection_static_routes
      - backup_prod_ipsec_display_name
      - backup_prod_ipsec_routing_type
      - backup_prod_private_subnet_cidr_block
      - backup_prod_public_subnet_cidr_block
      - backup_prod_retention_policy_duration_amount
      - backup_prod_retention_policy_duration_time_unit
      - backup_prod_shared_secret
      - backup_prod_spoke_subnet_app_cidr_block
      - backup_prod_spoke_subnet_db_cidr_block
      - backup_prod_spoke_subnet_web_cidr_block
      - backup_prod_spoke_vcn_cidr
      - backup_prod_tunnel_a_display_name
      - backup_prod_tunnel_b_display_name
      - backup_prod_vault_enable_replication
      - backup_prod_vault_replica_region
      - backup_prod_vault_type
      - backup_prod_workload_cidr
      - backup_provider_service_key_name
      - backup_service_gw_hub_check
      - backup_virtual_circuit_bandwidth_shape
      - backup_virtual_circuit_customer_asn
      - backup_virtual_circuit_display_name
      - backup_virtual_circuit_is_bfd_enabled
      - backup_virtual_circuit_type
      - is_create_alarms_backup
      - nonprod_enable_network_monitoring_alarms_backup
      - nonprod_enable_security_monitoring_alarms_backup
      - nonprod_enable_workload_monitoring_alarms_backup
      - nonprod_identity_topic_endpoints_backup
      - nonprod_network_topic_endpoints_backup
      - nonprod_platform_topic_endpoints_backup
      - nonprod_secops_topic_endpoints_backup
      - nonprod_workload_topic_endpoints_backup
      - prod_enable_network_monitoring_alarms_backup
      - prod_enable_security_monitoring_alarms_backup
      - prod_enable_workload_monitoring_alarms_backup
      - prod_identity_topic_endpoints_backup
      - prod_network_topic_endpoints_backup
      - prod_platform_topic_endpoints_backup
      - prod_secops_topic_endpoints_backup
      - prod_workload_topic_endpoints_backup
      - admin_domain_compartment_ocid
      - admin_domain_name
      - namespace_service_endpoint
      - nonprod_ag_license_type
      - nonprod_agcs_user_domain_name
      - nonprod_agcs_user_email
      - nonprod_agcs_user_fingerprint_oci_system
      - nonprod_agcs_user_group_display_name
      - nonprod_agcs_user_name
      - nonprod_agcs_user_ocid_oci_system
      - nonprod_agcs_user_private_key
      - nonprod_agcs_user_private_key_path
      - nonprod_agcs_user_region_oci_system
      - nonprod_agcs_user_tenancy_ocid_oci_system
      - nonprod_enable_access_governance
      - nonprod_oci_system_description
      - nonprod_oci_system_name
      - nonprod_service_instance_description
      - nonprod_service_instance_display_name
      - nonprod_use_existing_agcs_user
      - prod_ag_license_type
      - prod_agcs_user_domain_name
      - prod_agcs_user_email
      - prod_agcs_user_fingerprint_oci_system
      - prod_agcs_user_group_display_name
      - prod_agcs_user_name
      - prod_agcs_user_ocid_oci_system
      - prod_agcs_user_private_key
      - prod_agcs_user_private_key_path
      - prod_agcs_user_region_oci_system
      - prod_agcs_user_tenancy_ocid_oci_system
      - prod_enable_access_governance
      - prod_oci_system_description
      - prod_oci_system_name
      - prod_service_instance_description
      - prod_service_instance_display_name
      - prod_use_existing_agcs_user
      - should_create_connected_system
      - nonprod_retention_policy_duration_amount
      - nonprod_retention_policy_duration_time_unit
      - enable_network_firewall_nonprod
      - enable_traffic_threat_log_nonprod
      - enable_traffic_threat_log_prod
      - nfw_instance_name_nonprod
      - nfw_instance_name_prod
      - nfw_instance_policy_nonprod
      - nfw_instance_policy_prod
      - nfw_subnet_type_nonprod
      - nfw_subnet_type_prod
      - nfw_use_existing_network_nonprod
      - nfw_use_existing_network_prod
      - enable_datasafe
      - igw_hub_check
      - nat_gw_hub_check
      - nat_gw_spoke_check
      - nonprod_additional_workload_subnets_cidr_blocks
      - nonprod_application_admin_group_name
      - nonprod_bastion_client_cidr_block_allow_list
      - nonprod_budget_alert_rule_message
      - nonprod_budget_alert_rule_recipients
      - nonprod_budget_alert_rule_threshold
      - nonprod_budget_amount
      - nonprod_cost_center_tagging
      - nonprod_create_master_encryption_key
      - nonprod_database_admin_group_name
      - nonprod_domain_admin_email
      - nonprod_enable_bastion
      - nonprod_enable_budget
      - nonprod_enable_internet_gateway_hub
      - nonprod_enable_nat_gateway_hub
      - nonprod_enable_nat_gateway_spoke
      - nonprod_enable_network_monitoring_alarms
      - nonprod_enable_security_monitoring_alarms
      - nonprod_enable_service_gateway_hub
      - nonprod_enable_service_gateway_spoke
      - nonprod_enable_tagging
      - nonprod_enable_vault_replication
      - nonprod_enable_workload_monitoring_alarms
      - nonprod_external_master_encryption_key
      - nonprod_geo_location_tagging
      - nonprod_hub_private_subnet_cidr_block
      - nonprod_hub_private_subnet_dns_label
      - nonprod_hub_public_subnet_cidr_block
      - nonprod_hub_public_subnet_dns_label
      - nonprod_hub_vcn_cidr_block
      - nonprod_iam_admin_group_name
      - nonprod_identity_topic_endpoints
      - nonprod_network_admin_group_name
      - nonprod_network_topic_endpoints
      - nonprod_ops_admin_group_name
      - nonprod_platform_admin_group_name
      - nonprod_platform_topic_endpoints
      - nonprod_secops_topic_endpoints
      - nonprod_security_admin_group_name
      - nonprod_spoke_subnet_app_cidr_block
      - nonprod_spoke_subnet_db_cidr_block
      - nonprod_spoke_subnet_web_cidr_block
      - nonprod_spoke_vcn_cidr
      - nonprod_subnet_app_dns_label
      - nonprod_subnet_db_dns_label
      - nonprod_subnet_web_dns_label
      - nonprod_vault_replica_region
      - nonprod_vault_type
      - nonprod_workload_admin_group_name
      - nonprod_workload_compartment_names
      - nonprod_workload_topic_endpoints
      - prod_application_admin_group_name
      - prod_bastion_client_cidr_block_allow_list
      - prod_database_admin_group_name
      - prod_enable_bastion
      - prod_enable_nat_gateway_spoke
      - prod_enable_service_gateway_spoke
      - prod_enable_workload_monitoring_alarms
      - prod_hub_private_subnet_dns_label
      - prod_hub_public_subnet_dns_label
      - prod_spoke_subnet_app_cidr_block
      - prod_spoke_subnet_db_cidr_block
      - prod_spoke_subnet_web_cidr_block
      - prod_spoke_vcn_cidr
      - prod_subnet_app_dns_label
      - prod_subnet_db_dns_label
      - prod_subnet_web_dns_label
      - prod_workload_admin_group_name
      - prod_workload_topic_endpoints
      - service_gw_hub_check
      - service_gw_spoke_check
      - workload_name_prefix
      - nonprod_bgp_cust_tunnela_ip
      - nonprod_bgp_oci_tunnela_ip
      - nonprod_cpe_display_name
      - nonprod_cpe_ip_address
      - nonprod_cpe_vendor
      - nonprod_customer_bgp_asn
      - nonprod_enable_fastconnect
      - nonprod_enable_vpn
      - nonprod_ipsec_connection_static_routes
      - nonprod_ipsec_display_name
      - nonprod_ipsec_routing_type
      - nonprod_shared_secret
      - nonprod_tunnel_a_display_name
      - nonprod_tunnel_b_display_name
      - enable_landing_zone_replication
      - backup_region

variables:
  #Provider Variables
  region:
    type: string
    description: The OCI region LZ is deployed to
    title: Region
    required: true
  tenancy_ocid:
    type: string
    description: The OCID of tenancy
    title: Tenancy OCID
  current_user_ocid:
    type: string
    description: The OCID of the current user
    title: Current User OCID
    
  # Network Variables
  prod_environment_prefix:
    type: string
    description: "The prefix used for the new OELZ ENVIRONMENT"
    default: "CORP"
    required: true
    title: Landing Zone Environment Prefix
  prod_hub_vcn_cidr_block:
    type: string
    description: "VCN CIDR block in Hub"
    default: "10.1.0.0/24"
    required: true
    pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1][0-9]|[2][0-9]))$
    title: VCN CIDR Block in Hub
  prod_hub_public_subnet_cidr_block:
    type: string
    description: "Public subnet CIDR block in Hub VCN"
    default: "10.1.0.0/26"
    required: true
    pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1][0-9]|[2][0-9]))$
    title: Public Subnet CIDR Block in Hub VCN
  prod_hub_private_subnet_cidr_block:
    type: string
    description: "Private subnet CIDR block in Hub VCN"
    default: "10.1.0.64/26"
    required: true
    pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1][0-9]|[2][0-9]))$
    title: Private Subnet CIDR Block in Hub VCN
  enable_network_firewall_prod:
    type: string
    description: "Enable OCI network firewall in the Landing Zone environment"
    default: "false"
    required: true
    title: Enable OCI Network Firewall
